

<template>
    <div>

        <div class="mt-5 h3">Basic Form Example</div>
       

        <div class="mt-3 mb-3">The input for name uses the boolean 'state' property generated by a function to control the message associated with the input.<br/>  If state is valid (true) then the 'valid-feedback' property is shown. Otherwise the 'invalid-feedback' property is shown.<br/>
        Note that the 'state' property is used on both b-form-group and b-form-input and the validfeedback and invalid-feedback properties of b-form-group only.</div>

        <div class="mb-3">Apparently if you assign a function to 'state', 'invalid-feedback', and 'invalid-feedback' the functions must be reactive (not sure why) so make them 'computed'</div>

        <div class="mb-3">Note the three examples dealing with validation on input</div>  


        <b-form @submit.prevent="onSubmit" @reset="onReset" v-if="show">
      <b-form-group
        id="input-group-1"
        label="Email address:"
        label-for="input-1"
        description="We'll never share your email with anyone else."
      >
        <b-form-input
          id="input-1"
          v-model="form.email"
          type="email"
          placeholder="Enter email" 
          required
        ></b-form-input>
      </b-form-group>

      
      <b-form-group id="input-group-2" label="Example using strings for invalid-feedback and valid-feedback " label-for="input-2" :state="nameIsValid" invalid-feedback="invalidFeedback dude" valid-feedback="Feedback is valid - yes!"> 
        <b-form-input
          id="input-2"
          v-model="form.name"
          placeholder="Enter name"
       
          :state="nameIsValid"
        ></b-form-input>
      </b-form-group>

      <b-form-group id="input-group-5" label="Example using a function for invalid-feedback" label-for="input-5" :state="petTypeIsValid" :invalid-feedback="petInvalidMessage" valid-feedback="Pet type validated"> 
        <b-form-input
          id="input-5"
          v-model="form.pet"
          placeholder="Enter pet type"
       
          :state="petTypeIsValid"
        ></b-form-input>
      </b-form-group>


      <b-form-group id="input-group-6" label="Example using a function for invalid-feedback" label-for="input-6" :state="carMakerIsValid"> 
        <b-form-input
          id="input-6"
          v-model="form.car"
          placeholder="Enter car maker"
          :state="carMakerIsValid"
        ></b-form-input>
        <b-form-invalid-feedback>Sorry, Car maker is not valid</b-form-invalid-feedback>
        <b-form-valid-feedback>Great, Car maker is valid</b-form-valid-feedback>
      </b-form-group>



      <b-form-group id="input-group-3" label="Food:" label-for="input-3">
        <b-form-select
          id="input-3"
          v-model="form.food"
          :options="foods"
          required
        ></b-form-select>
      </b-form-group>

      <b-form-group id="input-group-4" v-slot="{ ariaDescribedby }">
        <b-form-checkbox-group
          v-model="form.checked"
          id="checkboxes-4"
          :aria-describedby="ariaDescribedby"
        >
          <b-form-checkbox value="me">Check me out</b-form-checkbox>
          <b-form-checkbox value="that">Check that out</b-form-checkbox>
        </b-form-checkbox-group>
      </b-form-group>

      <b-button type="submit" variant="primary">Submit</b-button>
      <b-button type="reset" variant="danger">Reset</b-button>
    </b-form>
    <b-card class="mt-3" header="Form Data Result">
      <pre class="m-0">{{ form }}</pre>
    </b-card>
  
    <h3>Name is {{  form.name  }}</h3>

</div>

  

   
  </template>

  <script>

import { ref, computed } from 'vue';


export default {
    name: 'form-example',
    setup() {

        //https://bootstrap-vue.org/docs/components/form-checkbox

        const form = ref({ 
            email: '',
            name: 'Cool Cat',
            food: null,
            pet: '',
            car: '',
            checked: []
        });

        const theName  = ref("")

        const foods = [{ text: 'Select One', value: null }, 'Carrots', 'Beans', 'Tomatoes', 'Corn'];

        const show = ref(true);


        const onSubmit = (event) => {
            alert('yes - money')
          //  event.preventDefault()
            alert(JSON.stringify(form))
        }

        const onReset = () => {}

        const nameIsValid = computed( _ => {
            console.log('executing nameIsValid with form',form);
            return form.value.name == "money"
        });

        const petTypeIsValid = computed( _ => {
           // console.log('executing nameIsValid with form',form);
            return form.value.pet == "bird"
        });

        const petInvalidMessage = computed(_ => {
          return "petInvalidMessage function put this here"
        });
        
        const carMakerIsValid = computed( _ => {
          return form.value.car == "Subaru"
        })

        return {form, foods, show, onSubmit, onReset, nameIsValid,  petTypeIsValid, petInvalidMessage, carMakerIsValid}

        
    }
}


</script>